# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LinkUs' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LinkUs
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'GoogleSignIn'
  pod 'SideMenu'
  pod 'iOSDropDown'
  pod 'MessageKit'
  pod 'Cosmos'
  pod 'JGProgressHUD'
  pod 'SDWebImage'

end
